-- ==========================================
-- 2. CATÁLOGOS BASE (Nivel 0)
-- ==========================================
CREATE TABLE area (
    cve_area INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_area_padre INT NULL,
    abreviatura VARCHAR(5) NOT NULL,
    nombre VARCHAR(60) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE tipo_profesor (
    cve_tipo_profesor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    descripcion TEXT
);

CREATE TABLE roles (
    cve_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE persona (
    cve_persona INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido_paterno VARCHAR(35),
    apellido_materno VARCHAR(35),
    cve_carrera INT,
    cve_nivel_estudio INT,
    fecha_alta TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE edificio (
    cve_edificio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80),
    abreviatura VARCHAR(5),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE tipo_aula (
    cve_tipo_aula INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(45) NOT NULL
);

CREATE TABLE tipos_bien (
    cve_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(2) NOT NULL,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE marcas (
    cve_marca INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_marca VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE motivo_de_movimiento (
    cve_motivo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_motivo VARCHAR(50) NOT NULL,
    requiere_aprobacion BOOLEAN DEFAULT FALSE
);

-- ==========================================
-- 3. TABLAS CON REFERENCIAS (Nivel 1)
-- ==========================================
CREATE TABLE profesor (
    cve_profesor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_persona INT NOT NULL REFERENCES persona(cve_persona),
    cve_tipo_profesor INT NOT NULL REFERENCES tipo_profesor(cve_tipo_profesor),
    cve_area INT REFERENCES area(cve_area),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE alumnos (
    cve_alumno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_persona INT NOT NULL REFERENCES persona(cve_persona),
    matricula VARCHAR(15) NOT NULL,
    fecha_inscrito DATE NOT NULL,
    inscrito BOOLEAN NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE usuarios (
    cve_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50) UNIQUE NOT NULL,
    contrasena_hash VARCHAR(255) NOT NULL,
    cve_rol INT REFERENCES roles(cve_rol),
    nombre VARCHAR(100),
    email VARCHAR(255),
    activo BOOLEAN DEFAULT true,
    cve_persona INT REFERENCES persona(cve_persona),
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE aula (
    cve_aula INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_edificio INT NOT NULL REFERENCES edificio(cve_edificio),
    cve_tipo_aula INT NOT NULL REFERENCES tipo_aula(cve_tipo_aula),
    cve_profesor INT REFERENCES profesor(cve_profesor),
    nombre VARCHAR(30) NOT NULL,
    codigo_barras varchar(50) unique, -- nuevo campo y único
    codigo_qr varchar(255) unique,    -- ahora es único
    capacidad SMALLINT
);

CREATE TABLE familias_articulos (
    cve_familia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(2) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cve_tipo INT REFERENCES tipos_bien(cve_tipo)
);

CREATE TABLE modelos (
    cve_modelo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_modelo VARCHAR(100) NOT NULL,
    cve_marca INT REFERENCES marcas(cve_marca),
    descripcion TEXT
);

CREATE TABLE adscripcion (
    cve_adscripcion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave_adscripcion VARCHAR(20) NOT NULL UNIQUE,
    nombre_adscripcion VARCHAR(50) NOT NULL,
    estado BOOLEAN DEFAULT TRUE,
    fecha_registro DATE DEFAULT CURRENT_DATE
);

-- ==========================================
-- 4. TABLAS CON REFERENCIAS (Nivel 2)
-- ==========================================
CREATE TABLE articulos (
    cve_articulo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave VARCHAR(4) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    cve_familia INT REFERENCES familias_articulos(cve_familia)
);

CREATE TABLE adscripcion_persona (
    cve_adscripcion_persona INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_adscripcion INT NOT NULL REFERENCES adscripcion(cve_adscripcion),
    cve_persona INT NOT NULL REFERENCES persona(cve_persona),
    activo BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- creación de la tabla folio_siia
create table folio_siia (
    cve_folio int generated by default as identity primary key,
    clave_siia varchar(50) not null,
    cve_persona int not null references persona(cve_persona),
    fecha date default current_date,
    hora time default current_time,
    estado boolean default true
);

-- creación de la tabla numero_resguardo
create table numero_resguardo (
    cve_resguardo_pk int generated by default as identity primary key,
    no_resguardo varchar(50) not null,
    cve_persona int not null references persona(cve_persona),
    fecha date default current_date,
    hora time default current_time,
    estado boolean default true,
    fecha_registro date default current_date

);


-- creación de la tabla bienes actualizada
create table bienes (
    cve_bien int generated by default as identity primary key,
    nombre varchar(100) not null,
    codigo_barras varchar(50) unique,
    nfc varchar(50) unique,
    codigo_qr varchar(255) unique,
    no_serie varchar(50) unique,
    no_factura varchar(50) unique,
    descripcion text,
    foto_url VARCHAR(500),
    foto_drive_id VARCHAR(255),
    cve_modelo int references modelos(cve_modelo),
    cve_articulo int references articulos(cve_articulo),
    costo_unitario decimal(10, 2),
    cve_aula int references aula(cve_aula),
    cve_encargado int references persona(cve_persona),
    estado_fisico varchar(20),        -- 'bueno', 'regular', 'malo', 'mantenimiento', 'baja'
    estado_prestamo varchar(20) default 'disponible',  -- 'disponible', 'prestado', 'reservado', 'vencido'
    activo boolean default true,
    fecha_registro date default current_date
);

-- ==========================================
-- 6. OPERACIONES (Movimientos)
-- ==========================================
CREATE TABLE auditorias (
    cve_auditoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_auditoria DATE DEFAULT CURRENT_DATE,
    cve_auditor INT REFERENCES persona(cve_persona),
    observaciones_generales TEXT
);

CREATE TABLE auditoria_detalle (
    cve_auditoria_det INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_auditoria INT REFERENCES auditorias(cve_auditoria),
    cve_bien INT REFERENCES bienes(cve_bien),
    encontrado BOOLEAN,
    estado_encontrado VARCHAR(50)
);

CREATE TABLE prestamos (
    cve_prestamo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_bien INT NOT NULL REFERENCES bienes(cve_bien),
    cve_persona_solicita INT NOT NULL REFERENCES persona(cve_persona),
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_devolucion_pactada TIMESTAMP,
    fecha_devolucion_real TIMESTAMP NULL,
    estado_prestamo VARCHAR(20) DEFAULT 'pendiente',
    observaciones TEXT
);

CREATE TABLE bitacora_movimientos (
    cve_movimiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cve_bien INT REFERENCES bienes(cve_bien),
    cve_motivo INT REFERENCES motivo_de_movimiento(cve_motivo),
    cve_persona_accion INT REFERENCES persona(cve_persona),
    fecha_movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    observaciones TEXT
);

-- ================================================================
-- 7. TRIGGERS (Lógica Automática)
-- ================================================================

-- A. Actualizar estado del bien según el préstamo
CREATE OR REPLACE FUNCTION fn_trg_actualizar_estado_prestamo()
RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.estado_prestamo = 'aprobado') THEN
        UPDATE bienes SET estado_prestamo = 'prestado' WHERE cve_bien = NEW.cve_bien;
    ELSIF (NEW.estado_prestamo = 'devuelto') THEN
        UPDATE bienes SET estado_prestamo = 'disponible' WHERE cve_bien = NEW.cve_bien;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_actualizar_estado_prestamo
AFTER UPDATE ON prestamos
FOR EACH ROW
EXECUTE FUNCTION fn_trg_actualizar_estado_prestamo();

-- B. Log automático de cambios de estado físico
CREATE OR REPLACE FUNCTION fn_trg_log_estado_fisico()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO bitacora_movimientos (cve_bien, cve_motivo, cve_persona_accion, fecha_movimiento, observaciones)
    VALUES (NEW.cve_bien, 1, 1, CURRENT_TIMESTAMP, 'El estado físico cambió a: ' || NEW.estado_fisico);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_log_estado_fisico
AFTER UPDATE ON bienes
FOR EACH ROW
WHEN (OLD.estado_fisico IS DISTINCT FROM NEW.estado_fisico)
EXECUTE FUNCTION fn_trg_log_estado_fisico();

-- ==========================================
-- 8. REGISTROS DE PRUEBA
-- ==========================================
INSERT INTO area (cve_area_padre, abreviatura, nombre) VALUES (NULL, 'DIR', 'Dirección General'), (1, 'SIST', 'Sistemas');
INSERT INTO tipo_profesor (nombre) VALUES ('TC'), ('AS');
INSERT INTO persona (nombre, apellido_paterno, apellido_materno) VALUES ('Juan', 'Perez', 'Lopez'), ('Maria', 'Gomez', 'Cruz'), ('Carlos', 'Ruiz', 'Mendez');
INSERT INTO profesor (cve_persona, cve_tipo_profesor, cve_area) VALUES (1, 1, 2);
INSERT INTO alumnos (cve_persona, matricula, fecha_inscrito, inscrito) VALUES (3, '202200123', '2022-08-15', TRUE);
INSERT INTO edificio (nombre, abreviatura) VALUES ('Edificio A', 'ED-A');
INSERT INTO tipo_aula (nombre) VALUES ('Aula Normal'), ('Laboratorio');
INSERT INTO aula (cve_edificio, cve_tipo_aula, nombre, capacidad) VALUES (1, 1, 'Aula A-101', 30);
INSERT INTO tipos_bien (clave, nombre) VALUES ('MC', 'Cómputo');
INSERT INTO familias_articulos (clave, nombre, cve_tipo) VALUES ('EQ', 'Equipos', 1);
INSERT INTO articulos (clave, nombre, cve_familia) VALUES ('LAP', 'Laptop', 1);
INSERT INTO marcas (nombre_marca) VALUES ('Dell');
INSERT INTO modelos (nombre_modelo, cve_marca) VALUES ('Latitude', 1);
INSERT INTO adscripcion (clave_adscripcion, nombre_adscripcion) VALUES ('ADS-001', 'Sistemas');
INSERT INTO motivo_de_movimiento (nombre_motivo, requiere_aprobacion) VALUES ('Cambio de estado', FALSE), ('Préstamo', TRUE);

INSERT INTO bienes (nombre, no_serie, cve_modelo, cve_articulo, cve_aula, estado_fisico) 
VALUES ('Laptop Dell Juan', 'SN-98765', 1, 1, 1, 'bueno');

INSERT INTO prestamos (cve_bien, cve_persona_solicita, fecha_devolucion_pactada) 
VALUES (1, 3, CURRENT_TIMESTAMP + INTERVAL '7 days');

INSERT INTO roles (nombre, descripcion) VALUES
    ('Administrador', 'Acceso total al sistema'),
    ('Profesor', 'Acceso a módulos de profesor'),
    ('Estudiante', 'Acceso básico a módulos de estudiante');

-- -----------------------------------------------------------------------------
-- Insertar Usuarios de Prueba
-- 
-- CONTRASEÑAS (usando password_hash):
-- - Admin123! -> $2y$10$...
-- - Profesor123! -> $2y$10$...
-- - Alumno123! -> $2y$10$...
-- 
-- Para verificar: password_verify('Admin123!', $hash)
-- -----------------------------------------------------------------------------
INSERT INTO usuarios (usuario, contrasena_hash, cve_rol, nombre, email, activo) VALUES
    ('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 1, 'Administrador del Sistema', 'admin@universidad.edu', true),
    ('profesor', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 2, 'Profesor de Ejemplo', 'profesor@universidad.edu', true),
    ('alumno', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 3, 'Estudiante de Ejemplo', 'alumno@universidad.edu', true)